### ISSUE TITLE
Building for x86|ARM

### ISSUE THREAD

**Issue by camnewnham** [microsoft/Azure-DevOps-YAML-for-Unity#1]
As noted in the yaml comments,

`  # TODO: Theoretically, could expect to use 'x86|ARM' to build for both HL1 and 2, but yet to get that to work.
  vs.appxPlatforms:         'ARM'`

I'm interested in helping to diagnose this and contribute to a solution. I've left some comments in the issue post here: https://issuetracker.unity3d.com/issues/uwp-building-multi-platform-appxbundle-via-msbuild-fails-with-il2cpp-scripting-backend which may be worth some discussion. Generally speaking it seems that while we specify multiple appxbundleplatform we can only correctly specify a single 'platform'.

I'm not able to correctly build an appxbundle or appxupload with x86|ARM on my local machine either, but specifying both Platform and AppxBundlePlatform (x86 or ARM) builds correctly.

**Comment by WikkidEdd** [comment]
Bundling multiple platforms can be achieved by adding `/p:UseSubFolderForOutputDirDuringMultiPlatformBuild=false ` to the end of the msbuild command.

**Comment by camnewnham** [comment]
Ah, I can confirm that this works locally so I assume it will in the pipeline too. Thanks Edd.
